[package]
name = "render-logic"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { "path" = "../engine" }
wgpu = "24.0.0"

[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "24.0.0", features = ["webgl"]}
