[package]
name = "break-main"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.29"
image = { version = "0.24", features = ["png"] }
engine = { path = "../engine" }
render-logic = { path = "../render-logic" }
async-rwlock = "1.3"
wgpu = "24.0.0"
